module.exports = {
  printWidth: 80,
  tabWidth: 2,
  trailingComma: 'all',
  singleQuote: true,
  semi: true,
  bracketSpacing: true,
  importOrder: [
    '^@/commands',
    '^@/commands/(.*)$',
    '^@/middlewares',
    '^@/middlewares/(.*)$',
    '^@/utils',
    '^@/utils/(.*)$',
    '^@/services',
    '^@/services/(.*)$',
    '^@/types',
    '<THIRD_PARTY_MODULES>',
  ],
  plugins: ['@trivago/prettier-plugin-sort-imports'],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
